name: Build Theos Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install dpkg ldid make

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Export Theos path
        run: echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build package
        run: |
          make clean package

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: tweak-package
          path: packages/*.deb
